version: '3'

services:
  render:
    build: ../
    image: render-app-image
    restart: unless-stopped
    ports:
      - 22634:22634
    # 80 exposed port from docker container
    container_name: render-app-container
    environment:
      - "LC_ADDR_fuseki_app=${LC_ADDR_fuseki_app}"
      - "LC_ADDR_geom2str_app=${LC_ADDR_geom2str_app}"
networks:
    default:
        external:
            name: scope-net


