
version: '3'
services:
  revit-app:
    build: .
    image: revit-app-image
    ports:
      - "22633:22633"
    container_name: revit-app-container
    environment:
      - "LC_ADDR_fuseki_app=${LC_ADDR_fuseki_app}"
networks:
    default:
        external:
            name: scope-net

